title: OmaMesh
description: Metro Omaha mesh community on Meshtastic and MeshCore.

# Optional nice-to-haves supported by GitHub Pages
plugins:
  - jekyll-feed
  - jekyll-seo-tag

author: "Scott Redd"

collections:
  bulletins:
    output: true
    permalink: /bulletins/:name/

defaults:
  - scope:
      path: ""
      type: bulletins
    values:
      layout: bulletin
